[install]
production = false   # keep devDependencies installed
optional = true
dev = true

[install.cache]
dir = "~/.bun/install/cache"  # directory to store cached dependencies
disable = false               # enable caching

[run]
bun = true
